name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta automáticamente todos los días
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Activity Graph SVG

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate SVG Graph
        uses: lowlighter/metrics@latest
        with:
          filename: github-activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
